// Generates components/icons/ from the raw Geist SVG exports in icons/svg/.
//
// The docs site is its own repo, so it cannot import the monorepo's private
// @fopost/icons package. The SVG exports and this generator are copied from it
// (packages/icons) and kept to the subset the docs actually render; the output
// is identical, so an icon looks the same here as it does in the app.
//
// Drop a new export into icons/svg/, then: npm run icons
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SVG_DIR = path.join(ROOT, 'icons', 'svg');
const OUT_DIR = path.join(ROOT, 'components', 'icons');

const pascal = (name) =>
  name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const JSX_ATTRS = {
  'fill-rule': 'fillRule',
  'clip-rule': 'clipRule',
  'clip-path': 'clipPath',
  'fill-opacity': 'fillOpacity',
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-opacity': 'strokeOpacity',
  'stroke-dasharray': 'strokeDasharray',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
};

// The ink Figma exported. Everything on this list becomes themeable.
const INK = new Set(['#666666', '#171717', '#121212', 'black', '#000000', '#000']);
const ACCENT = new Set(['#0068d6']);
const KNOCKOUT = new Set(['white', '#ffffff', '#fff']);

function recolor(content) {
  // A white fill inside a mask or clipPath is a stencil, not a knockout: leave it.
  let depth = 0;
  return content.replace(
    /<\/?(mask|clipPath)\b|(fill|stroke)="([^"]+)"/g,
    (match, block, attr, value) => {
      if (block) {
        depth += match.startsWith('</') ? -1 : 1;
        return match;
      }
      const v = value.toLowerCase();
      if (INK.has(v)) return `${attr}="currentColor"`;
      if (ACCENT.has(v)) return `${attr}="var(--icon-accent, currentColor)"`;
      if (KNOCKOUT.has(v) && depth === 0) return `${attr}="var(--background, #fff)"`;
      return match;
    },
  );
}

function toJsx(content, slug) {
  let out = recolor(content);
  // Namespace generated ids so two icons on one page cannot collide.
  const ids = [...out.matchAll(/id="([^"]+)"/g)].map((m) => m[1]);
  for (const id of ids) {
    const scoped = `${slug}-${id}`;
    out = out
      .split(`id="${id}"`)
      .join(`id="${scoped}"`)
      .split(`url(#${id})`)
      .join(`url(#${scoped})`);
  }
  out = out.replace(/style="mask-type:([a-z]+)"/g, "style={{ maskType: '$1' }}");
  for (const [from, to] of Object.entries(JSX_ATTRS)) {
    out = out.split(`${from}=`).join(`${to}=`);
  }
  return out
    .trim()
    .split('\n')
    .map((line) => `    ${line}`)
    .join('\n');
}

// Ids must be unique per rendered instance: the same mark can sit in a hidden
// menu and in the page at once, and a clip-path that resolves into a display:none
// subtree renders nothing. Components with ids read useId() and interpolate it.
function instanceIds(body) {
  const ids = [...body.matchAll(/id="([^"]+)"/g)].map((m) => m[1]);
  if (!ids.length) return { body, hasIds: false };
  for (const id of ids) {
    body = body
      .split(`id="${id}"`)
      .join('id={`${uid}' + id + '`}')
      .split(`="url(#${id})"`)
      .join('={`url(#${uid}' + id + ')`}')
      .split(`href="#${id}"`)
      .join('href={`#${uid}' + id + '`}');
  }
  return { body, hasIds: true };
}

function emit(name, viewBox, body) {
  const { body: b, hasIds } = instanceIds(body);
  if (!hasIds) {
    return `export const ${name} = (props: IconProps) => (\n  <svg {...ICON_BASE} viewBox="${viewBox}" {...props}>\n${b}\n  </svg>\n);`;
  }
  return `export const ${name} = (props: IconProps) => {\n  const uid = useId();\n  return (\n    <svg {...ICON_BASE} viewBox="${viewBox}" {...props}>\n${b}\n    </svg>\n  );\n};`;
}

const files = (await fs.readdir(SVG_DIR)).filter((f) => f.endsWith('.svg')).sort();

const icons = await Promise.all(
  files.map(async (file) => {
    const slug = file.replace(/\.svg$/, '');
    const raw = await fs.readFile(path.join(SVG_DIR, file), 'utf8');
    const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1];
    if (!viewBox) throw new Error(`${file}: no viewBox`);
    const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
    return { slug, component: `${pascal(slug)}Icon`, viewBox, body: toJsx(inner, slug) };
  }),
);

const banner = `// Generated by scripts/generate-icons.mjs. Do not edit by hand.
// Source: Geist icons by Vercel, exported from Figma, copied from the monorepo's
// packages/icons. Run: npm run icons
`;

await fs.mkdir(OUT_DIR, { recursive: true });

await fs.writeFile(
  path.join(OUT_DIR, 'index.tsx'),
  // useId is only imported when an icon actually needs a scoped id.
  `${banner}${icons.some(({ body }) => body.includes('id="')) ? "import { useId } from 'react';\n" : ''}import type { ComponentType, SVGProps } from 'react';

export type IconProps = SVGProps<SVGSVGElement>;
export type IconComponent = ComponentType<IconProps>;

// width/height in em so a Tailwind text-* class controls icon size, the way
// the app and the marketing site already do it. fill lives on the paths.
const ICON_BASE = {
  xmlns: 'http://www.w3.org/2000/svg',
  width: '1em',
  height: '1em',
  fill: 'none',
  'aria-hidden': true,
  focusable: false,
  style: { verticalAlign: '-0.125em', flexShrink: 0 },
} as const;

${icons.map(({ component, viewBox, body }) => emit(component, viewBox, body)).join('\n\n')}
`,
);

await fs.writeFile(
  path.join(OUT_DIR, 'registry.tsx'),
  `${banner}// Name-keyed lookup, for icons chosen from data (meta.json, frontmatter).
//
// SERVER COMPONENTS ONLY: this map references every icon, so importing it from
// a client component ships all of them. Client components import by name.
import {
${icons.map(({ component }) => `  ${component},`).join('\n')}
  type IconComponent,
  type IconProps,
} from './index';

export const ICONS: Record<string, IconComponent> = {
${icons.map(({ slug, component }) => `  ${JSON.stringify(slug)}: ${component},`).join('\n')}
};

export function Icon({ name, ...props }: IconProps & { name: string }) {
  const Component = ICONS[name];
  if (!Component) {
    if (process.env.NODE_ENV !== 'production') console.warn('Unknown icon: ' + name);
    return null;
  }
  return <Component {...props} />;
}
`,
);

console.log(`Generated ${icons.length} icons into components/icons/`);
