// Vendors the shared footer source from the sibling monorepo into
// components/marketing-footer/, so the Docker build of this site never needs
// the sibling checkout. Files are copied verbatim — tests/footer-sync.test.ts
// hash-compares them against the source whenever the sibling is present.
//
// Default source is ../fopost/packages/marketing-footer/src, which is how
// both the dev machine and the deploy server lay the repos out. During
// development against a monorepo worktree, pass the source dir explicitly:
//
//   node scripts/sync-footer.mjs <path-to-marketing-footer/src>
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.resolve(ROOT, process.argv[2] ?? '../fopost/packages/marketing-footer/src');
const OUT = path.join(ROOT, 'components', 'marketing-footer');

if (!fs.existsSync(SRC)) {
  console.error(`sync-footer: source not found: ${SRC}`);
  console.error('Expected the monorepo checked out as a sibling (../fopost).');
  process.exit(1);
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const files = fs.readdirSync(SRC).filter((f) => fs.statSync(path.join(SRC, f)).isFile());
for (const file of files) {
  fs.copyFileSync(path.join(SRC, file), path.join(OUT, file));
}

fs.writeFileSync(
  path.join(OUT, 'README.md'),
  `# DO NOT EDIT

Generated by \`npm run sync-footer\` from the monorepo's
\`packages/marketing-footer/src\` (checked out as \`../fopost\`).
Edit the source there, then re-run the sync. \`tests/footer-sync.test.ts\`
fails when this copy drifts from the sibling source.
`,
);

console.log(`sync-footer: copied ${files.length} files from ${SRC}`);
